name:  deployment to EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: get the enviromental variables
        run: echo "PORT=${{secrets.PORT}}" >> .env
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          tags: v1, latest
          image: wrashtech/fasty
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKENS }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull the image from docker-hub 
        run: docker pull wrashtech/fasty:latest
      - name: delete old fasty container
        run: docker rm -f wrashtech/fasty
      - name: run new container
        run: docker run -d -p 8000:8000 --name wrashtech/fasty wrashtech/fasty
      
