name:  deployment to EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: get the enviromental variables
        run: echo "PORT=${{secrets.PORT}}" >> .env
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Extract metadata 
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{secrets.DOCKER_USER}}/fasty
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/fasty
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull the image from docker-hub 
        run: docker pull wrashtech/fasty:latest
      - name: delete old fasty container
        run:  docker rm -f wrashtech/fasty
      - name: run new container
        run: docker run -d -p 8000:8000 wrashtech/fasty --name wrashtech/fasty
      
