name:  deployment to EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v2
      - name: get the enviromental variables
        run: echo "PORT=${{secrets.PORT}}" >> .env
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USER}}  -p ${{secrets.DOCKER_PASSWORD}}
      - name: build image
        run: docker build -t wrashtech/fasty .
      - name: push image
        run: docker push wrashtech/fasty:latest
       
     
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull the image from docker-hub 
        run: docker pull wrashtech/fasty:latest
      - name: delete old fasty container
        run: docker rm -f wrashtech/fasty
      - name: run new container
        run: docker run -d -p 8000:8000 --name wrashtech/fasty wrashtech/fasty
      
